In [ ]:
#Smart fridge example
temperature = 6 #temperature inside the fridge
if temperature >=10:
  print ("Turn on the cooling system")
elif temperature < 5:
   print ("Turn on Heating action ")
else:
  print("Temperature is fine, no action needed")

Temperature is fine, no action needed


In [ ]:
#Fan and timer example
for minute in range(1,6): #loop runs 5 times
    print (f"Minute{minute}:Fan is on.")
print("Fan turned off after 5 minutes")

Minute1:Fan is on.
Minute2:Fan is on.
Minute3:Fan is on.
Minute4:Fan is on.
Minute5:Fan is on.
Fan turned off after 5 minutes


In [ ]:
#If you want to use a fan until the room temperature drops below 25C
room_temp=30 # intial temperature
while room_temp>25:
   print("Fan is on to cool the room")
   room_temp=room_temp-1  # [room_temp-=1]assume the fan lowers the temperature by 1C per loop
print ("Fan turned off. Room temperature is now below 25C")

Fan is on to cool the room
Fan is on to cool the room
Fan is on to cool the room
Fan is on to cool the room
Fan is on to cool the room
Fan turned off. Room temperature is now below 25C


In [ ]:
from sklearn.decomposition import PCA
import numpy as np

X = np.array([[2, 4], [1, 3], [0, 1], [6, 8]])
pca = PCA(n_components=1)
X_transformed = pca.fit_transform(X)
print(X_transformed)

[[-0.16645248]
 [-1.5783838 ]
 [-3.73643653]
 [ 5.48127282]]


In [ ]:
import numpy as np

A = np.array([[0, 1, 0, 0],
              [0, 0, 1, 1],
              [1, 0, 0, 1],
              [1, 1, 0, 0]])

n = A.shape[0]
M = A / A.sum(axis=0)
v = np.ones(n) / n

for _ in range(100):
    v = np.dot(M, v)

print(v)


[0.17391304 0.34782609 0.2173913  0.26086957]


In [ ]:
from sklearn.linear_model import LinearRegression
import numpy as np

X = np.array([[1], [2], [3], [4], [5]])
y = np.array([2, 4, 6, 8, 10])

model = LinearRegression()
model.fit(X, y)

print(model.coef_, model.intercept_)


[2.] 0.0


In [4]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

inputs = np.array([[1, 0], [0, 1], [1, 1], [0, 0]])
outputs = np.array([[1], [1], [0], [0]])

weights = np.random.rand(2, 1)
bias = np.random.rand(1)
lr = 0.1

for _ in range(1000):
    layer = sigmoid(np.dot(inputs, weights) + bias)
    error = outputs - layer
    weights += lr * np.dot(inputs.T, error * sigmoid_derivative(layer))
    bias += lr * np.sum(error * sigmoid_derivative(layer))

print(weights, bias)


[[0.00919242]
 [0.00872962]] [-0.01060748]


In [5]:
import numpy as np

def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return np.where(x > 0, 1, 0)

X = np.array([[1, 0], [0, 1], [1, 1], [0, 0]])
y = np.array([[1], [1], [0], [0]])

weights = np.random.rand(2, 1)
bias = np.random.rand(1)
lr = 0.01

for _ in range(1000):
    layer = relu(np.dot(X, weights) + bias)
    error = y - layer
    weights += lr * np.dot(X.T, error * relu_derivative(layer))
    bias += lr * np.sum(error * relu_derivative(layer))

print(weights, bias)


[[0.00021803]
 [0.00022502]] [0.49973724]


In [4]:
import numpy as np

input_matrix = np.array([
    [4, 1, 3, 7],
    [2, 9, 8, 5],
    [6, 3, 2, 4],
    [1, 0, 7, 2]
])

def min_pooling(matrix, pool_size):
    output = []
    for i in range(0, matrix.shape[0], pool_size):
        row = []
        for j in range(0, matrix.shape[1], pool_size):
            row.append(np.min(matrix[i:i+pool_size, j:j+pool_size]))
        output.append(row)
    return np.array(output)

print(min_pooling(input_matrix, 2))


[[1 3]
 [0 2]]
